exports.AgentMessages = {
    GET_LIST: "List fetched successfully",
    PENDING_USER: "Fetched pending user's list successfully",
    AGENT_NOT_FOUND: "Agent not found",
    AGENT_ADDED : "Agent added successfully.",
    AGENT_ALREADY_ADDED: "Email already exist",
    ALREADY_ACCEPTED_INVITE:"User already accepted invite",
    INVITE_LINK: "Agent added and invitation link sent successfully.",
    INVALID_TOKEN: "Invalid token.",
    SET_PASSWORD: "Password set successfully.",
    GET_DATA: "Get data successfully.",
    AGENT_UPDATE: "Agent info updated successfully.",
    GROUP_ADDED : "Group added successfully.",
    GROUP_NAME_ALREADY_ADDED: "Group already exist.",
    GROUP_NOT_FOUND: "Group not found.",
    GROUP_MEMBER_ADDED : "Group member added successfully.",
    GROUP_UPDATE: "Group info updated successfully.",
    GROUP_DELETE: "Group deleted successfully.",
    ATTACHMENT_NOT_FOUND: "Attachment not found.",
    ATTACHMENT_DELETE: "Attachment deleted successfully.",
    AGENT_UPDATE: "Agent info updated successfully.",
    GROUP_MEMBER_NOT_FOUND: "Group member not found.",
    GROUP_MEMBER_DELETE: "Group member deleted successfully.",
    AGENT_ATTACHMENT_ADDED : "Agent attachment added successfully.",
    KYC_UPLOADED: "Kyc uploaded successfully.",
    CAPTURE_IMAGE_UPLOADED: "Captured image uploaded successfully.",
    PROFILE_COMPLETE: "Profile completed successfully.",
    AGENT_NOT_ACCESS: "You don't have permission to access this agent.",
    AGENT_STATUS_ALREADY: "Agent already",
    KYC_DETAIL_UPDATED: "Kyc detail updated successfully.",
    NOTE_CREATED: "Note added successfully.",
    NOTE_UPDATED: "Note updated successfully.",
    NOTE_NOT_FOUND: "Note not found",
    NOTE_DELETED: "Note deleted successfully.",
  };