exports.AuthMessages = {
    EMAIL_NOT_FOUND:"This email is not registered with us",
    EMAIL_EXIST:"Email already exist",
    INVALID_EMAIL:"Email is Invalid",
    PHONE_NUMBER_EXIST:"Phone number already exist",
    INVALID_PASSWORD:"Password is incorrect",
    INVALID_TOKEN:"Token is Invalid",
    LOGIN_SUCCESS:"User login successfully",
    FORGOT_PASSWORD_LINK:"Forgot password OTP sent on your registered email",
    RESET_PASSWORD:"Password reset successfully",
    WRONG_PASSWORD:"Old password is incorrect",
    NEW_PASSWORD_COMPARISON: "Your new password cannot be the same as your old password",
    PASSWORD_CHANGE_SUCCESS: "Password changed successfully",
    INVALID_USER: "Invalid User",
    UPDATE_INFO: "Account information updated successfully",
    DATA_NOT_FOUND: "Token not found",
    VALID: "Valid token",
    LOGOUT_SUCCESS:"User logout successfully.",
    INVALID_OTP:"Invalid OTP",
    OTP_VERIFIED:"OTP verified successfully.",
    CLIENT_NOT_FOUND: "Client not found.",
    CANCEL_STATUS: "You can't login. Your subscription has been cancelled.",
    TOKEN_SUCCESS:"Refresh token generated successfully",
    PASSWORD_NOT_SET:"Your password is not set. Please set your password.",
    NOT_CLIENT_EMAIL: "This is not a client email. Please use another email.",
    USER_NOT_FOUND: "User not found",
    STATUS_UPDATED: "Status updated successfully.",
    OTP_SEND:"Otp sent successfully to your email.",
    ACCOUNT_DISABLED: "We regret to inform you that your account has been inactive. Please contact our support team for further assistance.",
    GET_DATA: "Get data successfully.",
    COUNTRY_NOT_FOUND: "Country not found",
    OTP_EXPIRED:"OTP has been expired. Please resend otp.",
    RESEND_OTP:"OTP resend successfully.",
    PROFILE_DETAILS : "User Profile is get successfully.",
    PROFILE_UPDATED : "Profile is updated successfully.",
    ACCESS_GRANTED:"Access granted successfully",
    TWO_FACTOR_SETTING: "Setting updated successfully.",
    ROLE_AND_PERMISSION_ADDED: "Role and permissions added successfully.",
    ROLE_ALREADY_EXIST: "Role already exist.",
    ROLE_NOT_FOUND: "Role not found.",
    ROLE_DELETED: "Role deleted successfully.",
    ROLE_AND_PERMISSION_UPDATED: "Role and permissions updated successfully.",
    ROLE_CANNOT_DELETE: "This role is currently assigned to an Admin user and cannot be deleted.",
    ENABLE_ONE_PERMISSION: "Please select at least one option.",
    SUBSCRIPTION_SETTING: "Subscription settings updated successfully.",
    ROLE_PERMISSION_NOT_ACCESS: "You don't have permission to access this role.",
    NOTIFICATION_NOT_FOUND: "Notification not found.",
    NOTIFICATION_READ: "Notification read successfully.",
    NOTIFICATION_COUNT: "Get notification count successfully.",
    USER_ROLE_CANNOT_DELETE: "This role is currently assigned to a User and cannot be deleted.",
    SLACK_CHANNEL_SELECTED: "Channel select successfully for slack notifications.",
    USER_NOT_FOUND:"User not found.",
    ALREADY_INTEGRATE_SLACK:"You have already integrated.",
    SLACK_NOTIFICATION_TYPE_SAVED:"Slack notification types saved successfully.",
    GOOGLE_AUTHENTICATION_REQUIRED:"You haven't setup your google authentication.",
    CALENDAR_SYNC_SUCCESS:"Calendar synced successfully.",
    CALENDAR_UNSYNC_SUCCESS:"Calendar unsynced successfully.",
   

}