exports.ClientMessages = {
  GET_LIST: "list fetched successfully",
  DELETE_CLIENT: "Client deleted successfully",
  CLIENT_NOT_FOUND: "Client not found",
  INVITE_ALREADY: "Email already exist",
  NOT_DELETE_USER: "You can't delete this user",
  ALREADY_ACCEPTED_INVITE:"User already accepted invite",
  CLIENT_ADDED: "Client added successfully.",
  INVITE_LINK: "Client added and invitation link sent successfully.",
  INVALID_TOKEN: "Link has been expired.",
  SET_PASSWORD: "Password set successfully.",
  GET_DATA: "Get data successfully.",
  CLIENT_UPDATE: "Client info updated successfully.",
  AGENT_ASSINGNED: "Agent assigned to Client successfully.",
  AGENT_NOT_FOUND: "Agent not found",
  UNASSIGN_AGENT: "Agent unassign successfully.",
  NOT_ASSIGN_AGENT: "Agent not assigned to this client.",
  SUBSCRIPTION_ADDED: "Subscription created and payment link sent to client successfully.",
  SUBSCRIPTION_DATA: "Subscription data is not same in all objects. Please verify.",
  ACCOUNT_MANAGER_ASSINGNED: "Admin user assigned to Client successfully.",
  ACCOUNT_MANAGER_NOT_FOUND: "Admin user not found",
  NOT_ASSIGN_ACCOUNT_MANAGER: "Admin user is not assigned to this client.",
  UNASSIGN_ACCOUNT_MANAGER: "Admin user unassign successfully.",
  ACCOUNT_MANAGER_ALREADY_DEFAULT:" Admin user is already set as Default ",
  ACCOUNT_MANAGER_SET_DEFAULT:" Admin user is Set as Default Successfully",
  ACCOUNT_MANAGER_OR_CLINT_NOT_EXIST:" Admin user or Client is not exist",
  SUBSCRIPTION_NOT_FOUND: "Subscription not found",
  PAYMENT_FAILED: "Subscription not created. Please try again.",
  USER_NOT_FOUND: "User not found",
  PASSWORD_MANAGER_ADDED : "Credentials added successfully.",
  PASSWORD_MANAGER_UPDATED : "Credentials updated successfully",
  PASSWORD_MANAGER_NOT_EXIST : "Credentials is not Exist",
  PASSWORD_MANAGER_DELETED : "Credentials deleted successfully.",
  PASSWORD_MANAGER_DETAILS : "Password Manager details get successfully",
  FILE_NOT_CREATED : "File is not created",
  SHARED_FILE_CREATED : "Shared file is uploaded successfully",
  CANCEL_STATUS: "You can't login. Your subscription has been cancelled.",
  FILE_NOT_EXIST : "Shared file is not exist",
  FILE_DELETED : "Shared File is deleted successfully.",
  DEFAULT_ACCOUNT_MANAGER_NOT_FOUND : "The client does not have an assigned admin user.",
  DEFAULT_ACC_MANAGER : "Default admin user get successfully",
  CARD_ADDED : "Card added successfully",
  CARD_NOT_ADDED: "Invalid card.",
  CARD_DELETED : "Card deleted successfully.",
  CARD_UPDATED : "Card updated successfully",
  SUBSCRIPTION_CANCEL : "Subscription cancelled successfully.",
  SUBSCRIPTION_NOT_CANCEL : "Subscription is not cancelled. Please try again",
  SUBSCRIPTION_ALREADY_CANCEL: "Subscription already cancelled.",
  CARD_ALREADY_EXIST : "Card already exist.",
  SUBSCRIPTION_NOT_EDIT: "Subscription not updated. Please try again.",
  SUBSCRIPTION_UPDATED: "Subscription updated successfully.",
  SUBSCRIPTION_CANNOT_EDIT: "You can't updated this subscription.",
  SUBSCRIPTION_LINK_RESEND: "Subscription link resend successfully.",
  SUBSCRIPTION_LINK_NOT_SEND: "You can't send link of this Subscription. Because this is already paid.",
  REMINDER_UPDATED: "Reminder updated successfully.",
  TASK_ACCESS_ENABLED: "Task access enabled successfully.",
  TASK_ACCESS_DISABLED: "Task access disabled successfully.",
  PROJECT_NOT_FOUND: "Project not found.",
  SUBSCRIPTION_NOT_PAUSED: "You can't pause this subscription.",
  SUBSCRIPTION_PAUSED: "Subscription paused successfully",
  SUBSCRIPTION_NOT_PAUSED_ONE_TIME: "You can't pause this subscription.Because this is one time subscription.",
  SUBSCRIPTION_NOT_RESUME: "You can't resume this subscription.",
  SUBSCRIPTION_RESUMED: "Subscription resume successfully",
  NOT_ACCESS_FILE: "You are not authorized to access this file",
  FILE_ACCESSED: "File accessed successfully.",
  CLIENT_NOT_ACCESS: "You don't have permission to access this client.",
  CARD_CANNOT_DELETE: "Unable to remove the selected card. Ensure you have at least one active payment method before proceeding.",
  ROLE_ALREADY_EXIST: "Role already exist.",
  ENABLE_ONE_PERMISSION: "Please select at least one option.",
  ROLE_AND_PERMISSION_ADDED: "Role and permissions added successfully.",
  ROLE_AND_PERMISSION_UPDATED: "Role and permissions updated successfully.",
  ROLE_NOT_FOUND: "Role not found.",
  BANK_ADDED : "Bank added successfully",
  BANK_ALREADY_EXIST : "Bank already exist.",
  BANK_NOT_ADDED: "Invalid bank account.",
  BANK_UPDATED : "Bank updated successfully",
  CLIENT_REGISTERED: "You have registered successfully.",
  CARD_NOT_FOUND: "Card not found.",
  BANK_CANNOT_DELETE: "Unable to remove the selected bank. Ensure you have at least one active payment method before proceeding.",
  BANK_DELETED: "Bank deleted successfully.",
  BANK_NOT_FOUND: "Bank not found.",
};
