exports.ProjectMessages = {
    GET_LIST: "Get list successfully",
    PROJECT_NOT_FOUND: "Project not found",
    PROJECT_ADDED : "Project added successfully",
    GET_DATA: "Get data successfully.",
    PROJECT_UPDATE: "Project info updated successfully.",
    PROJECT_DELETE: "Project deleted successfully.",
    PROJECT_WHITEBOARD_ADDED : "Whiteboard added successfully.",
    PROJECT_WHITEBOARD_UPDATED : "Whiteboard updated successfully.",
    PROJECT_DOCUMENT_ADDED : "Document added successfully",
    PROJECT_DOCUMENT_UPDATED : "Document updated successfully",
    PROJECT_DOCUMENT_GET : " Document get successfully ",
    PROJECT_MENU_ADDED : "Menu added successfully.",
    PROJECT_MENU_NOT_FOUND: "Menu not found",
    PROJECT_MENU_UPDATE: "Menu updated successfully.",
    PROJECT_WHITEBOARD_DELETED : "Whiteboard deleted successfully",
    PROJECT_DOCUMENT_DELETED : "Document deleted successfully",
    PROJECT_MENU_DELETE: "Menu deleted successfully.",
    PROJECT_MENU_NOT_DELETE: "You can't deleted this menu.",
    PROJECT_MENU_PINNED: "Menu pinned successfully.",
    PROJECT_MENU_UNPINNED: "Menu unpinned successfully.",
    FILTER_NOT_FOUND: "Filter not found.",
    FILTER_DELETED: "Filter deleted successfully.",
    FILTER_UPDATED: "Filter updated successfully.",
  };