exports.SupportMessages = {
    SUPPORT_NOT_CREATED: "Support is not added.",
    SUPPORT_ADDED: "Ticket added successfully.",
    GET_LIST: "Get list successfully.",
    GET_DATA: "Data get successfully",
    DATA_NOT_FOUND: "Data not found.",
    SUPPORT_NOT_FOUND: "Ticket not found.",
    SUPPORT_DELETED: "Ticket deleted successfully.",
    SUPPORT_UPDATED: "Ticket updated successfully.",
    DEPARTMENT_ADDED: "Department added successfully.",
    DEPARTMENT_ALREADY_ADDED: "Department already added.",
    DEPARTMENT_NOT_FOUND: "Department not found.",
    DEPARTMENT_DELETED: "Department deleted successfully.",
    DEPARTMENT_UPDATED: "Department updated successfully.",
    SUPPORT_ATTACHMENT_NOT_FOUND: "Attachment not found.",
    SUPPORT_ATTACHMENT_DELETED: "Attachment deleted successfully.",
    KEYWORD_CREATED: "Keyword is created successfully",
    KEYWORD_LIST: "Keyword list get successfully",
    KEYWORD_UPDATED : "Keyword updated successfully",
    KEYWORD_NOT_EXIST : "Keyword is not exist",
    KEYWORD_DELETED : "Keyword is deleted successfully",
    KEYWORD_MAIL_SENT : "Keyword mail sent to Admin successfully.",
    KEYWORD_EMAIL_ADDED : "Keyword email added successfully.",
    SUPPORT_STATUS_CLOSE : "Support closed successfully.",
    SUPPORT_STATUS_OPEN : "Support open successfully.",
    RECEIVER_NOT_FOUND: "Receiver not found.",
    SUPPORT_STATUS_UPDATED: "Ticket status updated successfully.",
    SUPPORT_NOT_ACCESS: "You don't have permission to access this support.",

}