exports.TaskMessages = {
    TASK_ADDED : "Task added successfully",
    TASK_NOT_CREATED : "Something went wrong Task is not created",
    TASK_NOT_FOUND : "Task not found",
    GET_LIST: "Get list successfully",
    GET_DATA: "Get data successfully.",
    TASK_UPDATE: "Task updated successfully.",
    TASK_DELETE: "Task deleted successfully.",
    CLIENT_NOT_FOUND: "Client not found",
    PROJECT_NOT_EXIST  : "Project is not exist",
    PROJECT_COLUMN_NOT_EXIST  : "Project Column is not exist",
    AGENT_NOT_FOUND : "Agent not found",
    AGENTS_NOT_ASSIGNED : "Agents not Assigned to this Client",
    AGENTS_ALREADY_ASSIGNED : "Agents is already Assigned to this Task",
    FILE_NOT_FOUND: "File not found",
    FILE_DELETED: "File deleted successfully.",
    TASK_MOVE: "Task moved successfully.",
    TASK_ALREADY_EXIST_COLUMN: "Task already exist in this column",
    TASK_STATUS : "Task status updated successfully",
    COMPLETED_COLUMN_NOT_FOUND : "Completed column not found",
    TASK_COMPLETED: "Task completed successfully.",
    LABEL_ADDED: "Label added successfully.",
    LABEL_ALREADY_ADDED: "Label already added",
    CANNOT_COMPLETE_TASK : "You don't have permissions to complete this task.",
    CANNOT_MOVE_TASK : "You don't have permissions to move this task.",
    CANNOT_UPDATE_STATUS : "You don't have permissions to update status of this task.",
    LABEL_DELETED: "Label deleted successfully.",
    LABEL_NOT_FOUND: "Label not found.",
    TASK_MESSAGE_SEND: "Message sent successfully.",
    TASK_MESSAGE_NOT_SEND: "Message not sent. Please try again."

};