exports.UserMessages = {
  GET_LIST: "list fetched successfully",
  USER_ADDED : "User added successfully",
  INVALID_TOKEN: "Invalid token",
  SET_PROFILE: "Your profile updated successfully",
  INVITE_LINK: "User invite link sent to your registered email",
  LIST_USER: "Fetched user's list successfully",
  PENGDING_USER: "Fetched pending user's list successfully",
  DELETE_USER: "User deleted successfully",
  USER_NOT_FOUND: "User not found",
  USER_ALREADY_EXIST: "Email already exist.",
  NOT_DELETE_USER: "You can't delete this user",
  ALREADY_ACCEPTED_INVITE:"User already accepted invite",
  USER_DETAILS : "User detail get successfully.",
  USER_UPDATED : "User updated successfully.",
  LOGIN_CREDENTIALS_SENT : "User Credentials sent successfully.",
  USER_ROLE_NOT_FOUND: "User role not found",
  USER_OLD_PASSWORD_MATCH: "This is one of your old passwords. Please choose a new password.",
};
